[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brunch = "0.3.6"
itertools = "0.10.5"

[[bench]]
name = "bench"
harness = false